// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeck(arg1) {
  return window['go']['main']['App']['GetDeck'](arg1);
}

export function GetFileNames() {
  return window['go']['main']['App']['GetFileNames']();
}

export function GetFilePaths() {
  return window['go']['main']['App']['GetFilePaths']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendContext(arg1) {
  return window['go']['main']['App']['SendContext'](arg1);
}

export function UpdateState(arg1) {
  return window['go']['main']['App']['UpdateState'](arg1);
}
