// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckKey() {
  return window['go']['main']['App']['CheckKey']();
}

export function EditCard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditCard'](arg1, arg2, arg3, arg4);
}

export function GetDeck(arg1) {
  return window['go']['main']['App']['GetDeck'](arg1);
}

export function GetFileNames() {
  return window['go']['main']['App']['GetFileNames']();
}

export function GetFilePaths() {
  return window['go']['main']['App']['GetFilePaths']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResetProgress(arg1) {
  return window['go']['main']['App']['ResetProgress'](arg1);
}

export function RevertModel() {
  return window['go']['main']['App']['RevertModel']();
}

export function SaveKey(arg1, arg2) {
  return window['go']['main']['App']['SaveKey'](arg1, arg2);
}

export function SendContext(arg1) {
  return window['go']['main']['App']['SendContext'](arg1);
}

export function SendStudyBuddyMessage(arg1, arg2) {
  return window['go']['main']['App']['SendStudyBuddyMessage'](arg1, arg2);
}

export function UpdateState(arg1) {
  return window['go']['main']['App']['UpdateState'](arg1);
}
