// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckKey():Promise<boolean|string>;

export function EditCard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetDeck(arg1:string):Promise<main.Deck>;

export function GetFileNames():Promise<Array<string>>;

export function GetFilePaths():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ResetProgress(arg1:string):Promise<string>;

export function RevertModel():Promise<string>;

export function SaveKey(arg1:string,arg2:string):Promise<string>;

export function SendContext(arg1:main.Context):Promise<string>;

export function UpdateState(arg1:string):Promise<string>;
